### ISSUE TITLE
Add config parameter os.region

### ISSUE THREAD

**Issue by ggiamarchi** [ggiamarchi/vagrant-openstack-provider#128]
To make possible to specify the OpenStack region for endpoints selection.

**Comment by alanraison** [comment]
Hi. Is it possible to provision in two regions at once (i.e. with multiple machines)? It seems to me that the region is chosen before the multi-machine configuration is processed, but I might be wrong :)

**Comment by ggiamarchi** [comment]
@alanraison You're right, it doesn't work. The region of the first machine is used for the others even if you explicitly specify the region at the machine level.

As a workaround, you can run a command by machine. Let's say you have a Vagrantfile that looks like

```ruby
Vagrant.configure('2') do |config|
  config.vm.provider :openstack do |os|
    ...
  end

  config.vm.define 'server-1' do |s|
    s.vm.provider :openstack do |os|
      ...
      os.region = 'RegionOne'
    end
  end

  config.vm.define 'server-2' do |s|
    s.vm.provider :openstack do |os|
      ...
      os.region = 'RegionTwo'
    end
  end
end
```

Running

```
$ vagrant up server-1
$ vagrant up server-2
```

Will do the trick.

**Comment by jpdionne** [comment]
The issue in Openstack: https://bugs.launchpad.net/glance/+bug/1384379 https://review.openstack.org/#/c/206479/  .
