### ISSUE TITLE
Allow Wait Active timeout and retry interval to be configurable

### ISSUE THREAD

**Issue by nathairtras** [ggiamarchi/vagrant-openstack-provider#185]
The hard-coded value of 3.33 minutes is too short for our environment.  Allowing the end user to configure this value would help in dealing with less-than-optimal hosting arrangements.  Allowing the retry to be increased is nice in cases where you know you will need to wait for a while - it could either be set dynamically based upon the timeout, or manually entered.

Impacted file:
source/lib/vagrant-openstack-provider/action/wait_active.rb

Vagrant 1.6.5
vagrant-openstack-provider 0.6.0

**Comment by vinsh** [comment]
Good work on this feature!  Thanks!
