### ISSUE TITLE
Enhancement: Supporting NFS mounts?

### ISSUE THREAD

**Issue by jfbibeau** [ggiamarchi/vagrant-openstack-provider#203]
How hard would it be to support NFS mounts (just like the stock Vagrant providers) when the image is created with Openstack?

**Comment by ggiamarchi** [comment]
I'm not sure to understand what exactly you want to do. Do you want to use sync folders with `nfs` type like it is described in [this documentation](https://docs.vagrantup.com/v2/synced-folders/nfs.html) ?

To be honest i have never tried this Vagrant feature but i just had a look at the code and in my opinion this is not very complicated to implement in this provider as long as most of the code is already present in Vagrant itself.

The very important point to understand is that as the NFS server must be running on the host, the Vagrant machine should be able to access the host. This is easily achieved on Virtualbox using a private network but it is not as straightforward with an OpenStack instance, depending on where you OpenStack instance is and where you host is...

In my opinion this makes this feature not usable in most of the situation with OpenStack. However, if in your use case the host can contact the OpenStack instance, it can makes sense.

But i'm not opposed to support it.

**Comment by jfbibeau** [comment]
Thanks for the reply - love the responsiveness :)

Yes, in my case, my OpenStack deployment is running on a corporate network. So the floating IP which gets assigned from OpenStack to the vagrant box is quite reachable, in both direction. 

I agree with you that the NFS mount logic should already all be provided by Vagrant. It looks like it may just be a matter of enabling it in this provider so a user can select between rsync and NFS.

It would be nice to have as rsync is a "one time" sync on VM spin up, whereas NFS keeps the files constant between VM and host machine. This is useful for developer to share code real-time, etc... with the VM.

I'm not quite there with Ruby yet, but maybe I can take a look to see how hard it would be to implement.

**Comment by ggiamarchi** [comment]
The provider has moved to the standard vagrant synced folders middleware. I close all issues related to the legacy synced folders implementation. Feel free to comment/reopen this thread if you think you still get an issue related to this provider.
