### ISSUE TITLE
Access to obtained floating IP from provisioner phase.

### ISSUE THREAD

**Issue by kphonik** [ggiamarchi/vagrant-openstack-provider#205]
We're using the `floating_ip_pool` array to get the provider to snag an available IP for us. In our environment we don't have hostname/dns support configured so  we use the IP grabbed by the provider to access the VM.

While it's easy to snag the IP from vagrant via `vagrant ssh-config` or one of the provider commands - it doesn't seem possible to get that IP from within my shell provisioner where I need it.

The ability to pass the IPs into the shell provisioner `[:args]` attribute would be awesome!

**Comment by tacoben** [comment]
yes.  This.  Exactly This.  Yes.

**Comment by muzzy82** [comment]
Hi, 

Is there a similar method for other provisioners, e.g.: for ansible.

```ruby
  # Provision with ansible
  config.vm.provision :ansible do |ansible|
     ansible.playbook = "ansible_playbook/site.yml"
     ansible.extra_vars = {
         floating_ip: <floating ip here >
     }
  end

**Comment by devnewton** [comment]
ansible_ssh_host does not work for ansible_local provisionning.
