### ISSUE TITLE
Plugin always rsyncs a folder

### ISSUE THREAD

**Issue by jfbibeau** [ggiamarchi/vagrant-openstack-provider#207]
This plugin always wants to rsync the vagrant folder even though I tell it not to :)

```
  # Disable the current folder sharing
  config.vm.synced_folder ".", "/vagrant", disabled: true
```

But when it boots...

```
==> latest: The server is ready!
==> latest: Rsyncing folder: /home/vagrant/build-tools-openstack/vagrant/ => /vagrant
```

Design intent or a bug?

**Comment by ggiamarchi** [comment]
> Design intent or a bug?

In my opinion it's both... Actually, that's legacy because synced folders in this provider does not use the standard vagrant middleware and thus, none of the standard options are supported.

As a quick fix we can implement this `disabled` flag if you need it, but the long solution should be to completely reimplement the synced folders support.

**Comment by jfbibeau** [comment]
Okay, thanks for the explanation. I managed to workaround it so no need for a quick fix. 

Maybe this can be resolved when synced folders are re-implemented (with #203 NFS support? haha!)

**Comment by rds13** [comment]
Do you mean that despite the log nothing is synchronized ?

**Comment by jasonbrooks** [comment]
I've managed to get the plugin to stop trying to sync during vagrant up (using sync_method = "none") but it still wants to sync during provisioning -- I can't write to /vagrant on my image, so I can't provision. Maybe I'm using sync_method wrong?

**Comment by rds13** [comment]
As a matter of fact I do want to synchronize but not the default folder.
Anyway the current behaviour is not what you expect.

**Comment by ggiamarchi** [comment]
The provider has moved to the standard vagrant synced folders middleware. I close all issues related to the legacy synced folders implementation. Feel free to comment/reopen this thread if you think you still get an issue related to this provider.
