### ISSUE TITLE
Shared folder via rsync on Windows?

### ISSUE THREAD

**Issue by Semyazz** [ggiamarchi/vagrant-openstack-provider#213]
I have to run Vagrant on Windows host and I'd like to spawn both Virtualbox and OpenStack instances. Any ideas how can I sync files between Windows host and instance in OpenStack. Is there rsync for Windows?

**Comment by ggiamarchi** [comment]
On Windows you can get `rsync` using [Cygwin](https://www.cygwin.com).

**Comment by ggiamarchi** [comment]
The provider has moved to the standard vagrant synced folders middleware. I close all issues related to the legacy synced folders implementation. Feel free to comment/reopen this thread if you think you still get an issue related to this provider.
