### ISSUE TITLE
No support for OS_CACERT

### ISSUE THREAD

**Issue by patux** [ggiamarchi/vagrant-openstack-provider#222]
I tried to use the plugin with an openstack with OS_CACERT there is no such option for that that I am aware of

**Comment by julienvey** [comment]
You're right, there is no support for this currently. I added the "feature" tag

**Comment by VMTrooper** [comment]
Hello Julien,

Do you have an estimate on when this support can be added?

It would be of great interest to me as the OpenStack cloud that I work with requires the OS_CACERT environment variable.

Thanks!
Trevor

**Comment by patux** [comment]
julien, would be nice if you say where to start to add that feature...
which files to touch or what are the caveats you see

**Comment by VMTrooper** [comment]
Hello Folks,

This feature is not necessary if you create a Root CA for your dev lab, generate a csr for your OpenStack environment, and sign the csr yourself.

After importing my "signed" certificate file to my desktop's keychain, I no longer need to use the OS_CACERT environment variable.  I can provision instances with the other Vagrant OpenStack plugin, and I'm sure the same will be true for vagrant-openstack-provider as well.

This is the quickest resolution for a dev lab. Of course, in production, make sure to get a real CA-signed certificate.

Thanks,
Trevor

**Comment by julienvey** [comment]
@VMTrooper @patux I'm not working on this feature right now but here are some insights about where this feature should be added in the code

First, the `ca_cert` config option should be added in [config.rb](https://github.com/ggiamarchi/vagrant-openstack-provider/blob/master/source/lib/vagrant-openstack-provider/config.rb)

This would extend the Vagrantfile and we could do

```ruby
config.vm.provider :openstack do |os|
  os.ca_cert = '/path/to/my/cert'
end
```

After that, we would need to tell the http lib (we are using rest-client in this provider) about this ca_cert. Here is the documentation https://github.com/rest-client/rest-client#ssl-client-certificates
We would probably need to update [this file](https://github.com/ggiamarchi/vagrant-openstack-provider/blob/master/source/lib/vagrant-openstack-provider/client/rest_utils.rb)

This [feature](https://github.com/ggiamarchi/vagrant-openstack-provider/issues/85) would also do the job but is just a workaround

**Comment by patux** [comment]
thanks a lot for the info Julien
