### ISSUE TITLE
Timeout for waiting a newly created machine always defaults to 180, doesn't recognize the timout options

### ISSUE THREAD

**Issue by theratboss** [ggiamarchi/vagrant-openstack-provider#225]
When building a new machine and watching the console it still boots up, while vagrant is waiting for ssh to become available. Neither of the options for tameout is set into account:
 config.vm.boot_timeout= 800
    os.server_active_timeout =  400
    os.server_create_timeout =  600
 the message is always the same that it reached the default of 180 and it will not wait any longer.

Versions:
Vagrant 1.4
openstack provider 0.6.1
 
Command:
vagrant up testvm2 --provider=openstack

Output:
Bringing machine 'testvm2' up with 'openstack' provider...
[testvm2] Finding flavor for server...
[testvm2] Finding image for server...
[testvm2] Launching a server with the following settings...
[testvm2]  -- Tenant          : demo
[testvm2]  -- Name            : testvm2
[testvm2]  -- Flavor          : m1.small
[testvm2]  -- FlavorRef       : 2
[testvm2]  -- Image           : ubuntu-14.04-server-cloudimg-amd64-disk1
[testvm2]  -- ImageRef        : 117b0530-b6a6-4c9c-9a52-590666c825dd
[testvm2]  -- KeyPair         : vagrant-generated-mdykv6sq
[testvm2] Waiting for the server to be built...
[testvm2] Using floating IP 172.24.4.13

[testvm2] Waiting for SSH to become available...
[testvm2] Waiting for SSH to become available...
....
[testvm2] Waiting for SSH to become available...
[testvm2] Timeout!
SSH server anavailable on instance 172.24.4.5. You should maybe increase the timeout value which currently is 180 second(s).

Vagrant file:
Vagrant.configure('2') do |config|

  config.vm.box       = 'openstack'
  config.ssh.username = 'ubuntu'
  config.ssh.private_key_path = 'XXXX'
  config.vm.boot_timeout= 800

  config.vm.provider :openstack do |os|
    os.openstack_auth_url = 'XXXXXXXXs'
    os.username           = 'XXXX'
    os.password           = 'XXXX'
    os.tenant_name        = 'XXX'
    os.flavor             = 'm1.small'
    os.image              = 'ubuntu-14.04-server-cloudimg-amd64-disk1'
    os.floating_ip_pool   = 'public'
    os.public_key_path = 'XXXX'
    os.server_active_timeout =  400
    os.server_create_timeout =  600
  end

  config.vm.define "testvm2" do |testvm2|
  end

end

**Comment by ggiamarchi** [comment]
Actually, the timeout option for SSH `os.ssh_timeout`. I've just realized it is not documented. Keeping this issue open for documentation update.

**Comment by ggiamarchi** [comment]
The standard option `config.vm.boot_timeout` is currently not supported. i've created #227 for that.
