### ISSUE TITLE
Support for trove mechanics

### ISSUE THREAD

**Issue by iamkobold** [ggiamarchi/vagrant-openstack-provider#247]
Looking for interest in supporting some of the trove mechanics for setting up database resources using openstack/vagrant. Trove VM's seem to be special ones as I can boot one but i seem to have issues executing commands for the database to like re-create the database and what not? 

One of the use cases I am doing is setting up a multi-machine topology with a trove database using vagrant I currently have a trove image already running in the openstack tenant. However,  i have no real way to automatically create/destroy databases and or users with normal vagrant up/down functions

Thoughts on how to do this with the openstack plugin as is or should this be a feature like how volumes can be attached and what not?

**Comment by ggiamarchi** [comment]
This feature is interesting but looks to be out of scope. Maybe a tool like terraform is more appropriate.
