### ISSUE TITLE
Support standard synced folder middleware (fixes various bugs / missing features)

### ISSUE THREAD

**Issue by maxlinc** [ggiamarchi/vagrant-openstack-provider#257]
I was going to report that `vagrant rsync` and `vagrant rsync-auto` commands do not work when using the openstack provider. I'm pretty sure this is one of several bugs / side-effects of what @ggiamarchi wrote in #207:

> synced folders in this provider does not use the standard vagrant middleware

I did work to fix this a while back on the Vagrant-Rackspace plugin, along with some other things to make the plugin work better with Vagrant 1.5+. You can see all those changes in https://github.com/mitchellh/vagrant-rackspace/pull/129, but I believe the relevant commit was https://github.com/maxlinc/vagrant-rackspace/commit/15abef8025d3e832bec7eaafed7d253acfd2dece.

**Comment by menrcom** [comment]
Also, initial sync during `vagrant up` doesn't work in case if rsync isn't installed in VM image.
Usual behaviour for vagrant is to install rsync if it is missing, as I know. But with openstack provider this doesn't happen.

**Comment by ggiamarchi** [comment]
Fixed by https://github.com/ggiamarchi/vagrant-openstack-provider/pull/295
