### ISSUE TITLE
Version of json needs upgraded

### ISSUE THREAD

**Issue by justicel** [ggiamarchi/vagrant-openstack-provider#265]
Hello, the 1.7.7 version of json that you are including does not compile with the new Vagrant 1.8.0. A simple upgrade to one of the 1.8.x releases should fix this!

**Comment by artem-sidorenko** [comment]
@ggiamarchi is it possible for you provide any estimation on this? This breaks the usage on new vagrant versions completely. The fix should be quite simple, I can provide a PR if you like

**Comment by artem-sidorenko** [comment]
there is already a PR #268

**Comment by ggiamarchi** [comment]
Fixed by #268
