### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by shubhamrajvanshi** [ggiamarchi/vagrant-openstack-provider#266]
While installing plugin I get below error. Can someone help me or let me know if it is a known issue and if there is a workaround. I am getting this on Mac with OS X

vagrant plugin install vagrant-openstack-provider
Installing the 'vagrant-openstack-provider' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing json (1.7.7), and Bundler cannot continue.
Make sure that `gem install json -v '1.7.7'` succeeds before bundling.

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /opt/vagrant/embedded/bin/ruby -r ./siteconf20151222-11710-15a6seo.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling generator.c
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:47: error: too few arguments provided to function-like macro invocation
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                              ^
/opt/vagrant/embedded/include/ruby-2.2.0/ruby/intern.h:793:9: note: macro 'rb_str_new' defined here
#define rb_str_new(str, len) __extension__ (    \
        ^
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:11: warning: incompatible pointer to integer conversion initializing 'VALUE' (aka 'unsigned long') with an expression of type 'VALUE (const char *, long)' [-Wint-conversion]
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
          ^        ~~~~~~~~~~
1 warning and 1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/shubham/.vagrant.d/gems/gems/json-1.7.7 for inspection.
Results logged to /Users/shubham/.vagrant.d/gems/extensions/universal-darwin-12/2.2.0/json-1.7.7/gem_make.out

**Comment by sawahashi2000** [comment]
I have experienced same issue but I couldn't install yet.
I could install the plugin with Vagrant 1.7.4 which is older version.
You can get from the below URL. Let try it!
https://releases.hashicorp.com/vagrant/

**Comment by v1k0d3n** [comment]
@sawahashi2000 recommendation was the only solution that worked for me (without a lot of work). just went back to version 1.7.4...unfortunately that's the only easy solution until this is upgrade for v1.8.

**Comment by Roming22** [comment]
I confirm the issue, and that installing Vagrant 1.7.4 solves the problem.

**Comment by jhoblitt** [comment]
#268 Resolves this

**Comment by ggiamarchi** [comment]
Fixed by #268
