### ISSUE TITLE
Unable to use custom image for openstack

### ISSUE THREAD

**Issue by mchawre** [ggiamarchi/vagrant-openstack-provider#270]
I want to create instances on openstack using a custom image that is located remotely on some location like artifactory.
Is there any way to just provide a link of the image to vagrant-openstack-provider and the vagrant will pick up and download the image while bringing up the instances on openstack.

**Comment by jfbibeau** [comment]
As far as I know, your image already has to be in Openstack (glance). I don't think there's a way for vagrant to download the image from artifactory and upload it to glance, that seems a bit outside the scope :)

**Comment by ggiamarchi** [comment]
There's actually a spec for that purpose described in #164. But not implemented so far. Closing this one, given that another issue exists.
