### ISSUE TITLE
rsync excludes cannot be overridden

### ISSUE THREAD

**Issue by aaronboyle** [ggiamarchi/vagrant-openstack-provider#291]
When using rsync as the sync_method, exclude rules related to version control are hard-coded and I am not provided an option to change this.  In particular the --cvs-exclude option excludes any folder named 'tags', which my java application requires to run.

In my opinion, a better design decision would be to remove the default exclude rules entirely.  Any user who desires exclude rules can specify them in the Vagrantfile.  For my purposes being able to specify 'no excludes' would also be sufficient, as would removing the --cvs-exclude option from https://github.com/ggiamarchi/vagrant-openstack-provider/blob/master/source/lib/vagrant-openstack-provider/action/sync_folders.rb#L99 .

Steps to reproduce:
- Configure required openstack bits in Vagrantfile.
- include the line: config.vm.synced_folder '.', '/vagrant', type: 'rsync', rsync__exclude: '.git/'
  OR leave this line blank because the openstack provider chooses rsync by default
- create a folder in any subdirectory of the vagrant root named 'tags'
- do vagrant up --provider=openstack
- login and observe that the 'tags' folder is absent

Expected behavior:
  Files that I do not specifically exclude should be present in /vagrant

Actual behavior:
  Any files that match the rsync-exclude ruleset (among others) are absent from /vagrant

**Comment by aaronboyle** [comment]
I have also attempted to work around this by setting rsync_includes to 'tags' or '*' but unfortunately this does not override the rsync exclude command line options.

**Comment by aaronboyle** [comment]
https://github.com/ggiamarchi/vagrant-openstack-provider/pull/292

**Comment by ggiamarchi** [comment]
The provider has moved to the standard vagrant synced folders middleware. I close all issues related to the legacy synced folders implementation. Feel free to comment/reopen this thread if you think you still get an issue related to this provider.
