### ISSUE TITLE
ssh options are not passed to rsync

### ISSUE THREAD

**Issue by nnashok** [ggiamarchi/vagrant-openstack-provider#300]
I have to connect to my instance through an ssh gateway. `vagrant` itself supports by allowing me to specify the `proxy_command`. However, this provider plugin does not pass on the ssh options to the `rsync` command executed when synching folders. If I edit the `action/sync_folders.rb`, to add the `ProxyCommand`, then everything works.

This should be done by the plugin automatically and include other options configured for rsync/synched_folders in the Vagrantfile.

**Comment by ggiamarchi** [comment]
The provider has moved to the standard vagrant synced folders middleware. I close all issues related to the legacy synced folders implementation. Feel free to comment/reopen this thread if you think you still get an issue related to this provider.
