### ISSUE TITLE
Rsync is broken on msys2 (and maybe others)

### ISSUE THREAD

**Issue by baderas** [ggiamarchi/vagrant-openstack-provider#304]
When using vagrant-openstack-provider on Windows with msys2, the following error occurs:

```
default: Rsyncing folder: XXXXXXXXXX => /vagrant
There was an error when attempting to rsync a share folder.
Please inspect the error message below for more info.

Host path: XXXXXXXXXX
Guest path: /vagrant
Error: This rsync lacks old-style --compress due to its external zlib.  Try -zz.
Continuing without compression.
```

`VAGRANT_LOG=info vagrant up --provider=openstack --debug` showed me that it is a msys2 related issue: /cygwin/c/... does not exist in msys2.
I also tried workarounds with binding the folders so that they exist but that all did not work.

The [sync_folders.rb](problematic lines in source/lib/vagrant-openstack-provider/action/sync_folders.rb) are those:

```
# If on Windows, modify the path to work with cygwin rsync
if @host_os =~ /mswin|mingw|cygwin/
    hostpath = add_cygdrive_prefix_to_path(hostpath)
end
```

They should recognize msys2 and not add the prefix.

Versions:
vagrant 1.8.5
rsync version 3.1.2 protocol version 31

See also https://github.com/mitchellh/vagrant/issues/6702

**Comment by ggiamarchi** [comment]
The provider has moved to the standard vagrant synced folders middleware. I close all issues related to the legacy synced folders implementation. Feel free to comment/reopen this thread if you think you still get an issue related to this provider.
