### ISSUE TITLE
Full Keystone v3 support

### ISSUE THREAD

**Issue by ggiamarchi** [ggiamarchi/vagrant-openstack-provider#334]
Currently, Keystone v3 is partially supported. It works only if the project's domain and the user's domain are the same.

**Comment by furlongm** [comment]
+1 for this feature

**Comment by greg-hellings** [comment]
How does this problem manifest itself? I'm hitting an issue where provisioning gets part way through, then throws an exception connecting to one of the services with an error of ``Failed to open TCP connection to [host redacted]:13774 (getaddrinfo: Name or service not known)``. I can open a connection there through telnet without a problem.

Am I running into this problem, or is this something else? (Using released 0.11.0 version)
