### ISSUE TITLE
Release 0.11.0

### ISSUE THREAD

**Issue by akitada** [ggiamarchi/vagrant-openstack-provider#335]
There are some good features/fixes on master that would be great improvements over 0.10.0.

Please consider releasing a new version.

**Comment by ggiamarchi** [comment]
I totally agree! The released will be published soon.

**Comment by Transrian** [comment]
Agree, I need the parameter **ssl_verify_peer** to make it work in prod

**Comment by ggiamarchi** [comment]
Release 0.11.0 is published! Sorry guys for the late publish...
