### ISSUE TITLE
How to launch multiple nodes in parallel as supported by vagrant AWS plugin

### ISSUE THREAD

**Issue by shubhamrajvanshi** [ggiamarchi/vagrant-openstack-provider#351]

**Comment by ggiamarchi** [comment]
This feature had been implemented 4 months ago but it was not published in a release. It's done now. Available in release `0.12.0`. Update the plugin in your environment and it will be available using the standard option `vagrant up --parallel`.

See #339

**Comment by shubhamrajvanshi** [comment]
Thanks for the info will give it a try.

**Comment by shubhamrajvanshi** [comment]
Thanks, I was able to verify it and deploy in parallel. It saved me 1 hour after your change.

**Comment by ggiamarchi** [comment]
Glad to hear that 👌
