### ISSUE TITLE
hello I would like to collaborate with your project by serving as a translator to Spanish

### ISSUE THREAD

**Issue by LuigiBaute** [ggiamarchi/vagrant-openstack-provider#353]

**Comment by ggiamarchi** [comment]
Hi @LuigiBaute,

Help is always welcome! So far we didn't work on translation but from a technical point of view the application is already i18n. Strings are externalized in a YAML file. If you open a pull request with a spanish version of [source/locales/en.yml](https://github.com/ggiamarchi/vagrant-openstack-provider/blob/master/source/locales/en.yml) I will make sure it is integrated.
