### ISSUE TITLE
Allow Neutron to manage floating IPs

### ISSUE THREAD

**Issue by matttrach** [ggiamarchi/vagrant-openstack-provider#366]
https://developer.openstack.org/api-ref/network/v2/
https://developer.openstack.org/api-ref/network/v2/#create-floating-ip
The floating IP allocation via Nova has been deprecated, how hard would it be to get the Neutron API to manage them?

**Comment by ggiamarchi** [comment]
There's some work... But I definitely agree, it is necessary. We should use Neutron in priority and fallback on nova-network for legacy OpenStack platforms
