### ISSUE TITLE
Support keystone v3

### ISSUE THREAD

**Issue by ggiamarchi** [ggiamarchi/vagrant-openstack-provider#4]

**Comment by stuart-warren** [comment]
I've hacked this plugin to work with keystone v3, but it's pretty ugly (and ruby isn't a strong skill of mine)

Main changes are 
* in config.rb to accept a domain and currently an auth_api version
* in client/keystone.rb to create the correct post_body for the auth_api version and get the token/catalog correctly
* in catalog/openstack_catalog.rb to correctly parse the output depending on auth_api version

How do you propose handling the different versions?
stuart-warren/vagrant-openstack-provider@551384615bbdcb01b831b07563276960c25820b7

**Comment by degano** [comment]
@ggiamarchi is there any chance this feature will see the daylight? In my organization we are using @stuart-warren patch and it's working for us where we specifically need both versions to be supported.
The change is not too big, maybe it shouldn't be so time-consuming to merge and refine it?

**Comment by ggiamarchi** [comment]
@degano The pull request https://github.com/ggiamarchi/vagrant-openstack-provider/pull/307 has been submitted to implement this feature. I plan to do the review this week
